- hosts: all
  vars_files:
    - embassy_vars.yml
  user: root
  tasks:
  - name: copy the rpm
    action: copy src=files/embassy.rpm dest=/tmp/embassy.rpm  
  - name: install the rpm
    action: command alien -i /tmp/embassy.rpm
  - name: Configuring emb.xml
    action: template src=templates/embassy.xml.j2 dest=$conf_dir/Catalina/localhost/embassy.xml
  - name: Configuring server.xml
    action: template src=templates/tomcat_server.xml.j2 dest=$conf_dir/server.xml
  - name: Copy truststore
    action: copy src=files/$truststore dest=$conf_dir/$truststore owner=root group=root mode=0666
  - name: Create app-conf directory
    action: file path=$embassy_dir/app-conf owner=root group=root state=directory
  - name: Configure logback.xml
    action: template src=templates/logback.xml.j2 dest=$embassy_dir/app-conf/logback.xml
