- hosts: all
  vars:
    master_address: 127.0.0.1/705
  vars_files:
    - embassy_vars.yml
  user: root
  tasks:
  - name: copy the rpm
    action: copy src=embassy.rpm dest=/tmp/embassy.rpm  
  - name: install the rpm
    action: command alien -i /tmp/embassy.rpm
#  - name: Deployment template file
#    action: template src=templates/emb.xml.j2 dest=/opt/emb.xml
