- hosts: all
  vars:
    master_address: 127.0.0.1/705
  vars_files:
    - embassy_vars.yml
  user: root
  tasks:
  - name: Configuring emb.xml
    action: template src=templates/emb.xml.j2 dest=$embassy_dir/emb.xml
  - name: Configuring server.xml
    action: template src=templates/tomcat_server.xml.j2 dest=$embassy_dir/server.xml
